name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install compiler
      run: sudo apt-get update && sudo apt-get install build-essential

    - name: Build all programs
      run: make all # 'all' is the default target, so 'make' also works

